"""Hourly {{title}} ingest. Generated by datum-kit on {{today}}.

Fill in fetch_rows(): return one dict per entity with keys entity_id, entity_name, chain, value_usd,
secondary_usd, rate_pct, payload. Everything else (run logging, freshness, append-only insert) is done.

  DATABASE_URL=... python scripts/ingest_{{schema}}.py
"""
import os, sys, json, time, datetime as dt
import requests, psycopg2, psycopg2.extras

SOURCE_ID = '{{source_id}}'
EXPECTED_HOURS = 3          # freshness: how stale this source may be before Setnel flags it
URL = os.environ.get('{{SCHEMA_UPPER}}_URL') or '{{url}}'

def http(method, url, tries=4, **kw):
    last = None
    for i in range(tries):
        try:
            r = requests.request(method, url, timeout=60, **kw); last = r
            if r.status_code == 200: return r.json()
        except requests.RequestException as e:
            last = e
        time.sleep(2 * (i + 1))
    raise RuntimeError(f'{url} failed: {getattr(last, "status_code", last)}')

QUERY = """query($first:Int!, $skip:Int!){ items(first:$first, skip:$skip){ id name chain { name } tvlUsd borrowUsd apy } }"""

def fetch_rows():
    """GraphQL example with first/skip paging. Replace QUERY, the root field and the mapping."""
    out, skip = [], 0
    while True:
        page = http('POST', URL, json={'query': QUERY, 'variables': {'first': 100, 'skip': skip}}).get('data', {}).get('items') or []
        for it in page:
            out.append({'entity_id': str(it['id']), 'entity_name': it.get('name'), 'chain': (it.get('chain') or {}).get('name'),
                        'value_usd': _num(it.get('tvlUsd')), 'secondary_usd': _num(it.get('borrowUsd')), 'rate_pct': _pct(it.get('apy')), 'payload': it})
        if len(page) < 100: break
        skip += 100
    return out

def _num(v):
    try: return None if v is None else float(v)
    except (TypeError, ValueError): return None
def _pct(v):
    n = _num(v); return None if n is None else (n * 100 if abs(n) <= 1 else n)

def main():
    url = os.environ.get('DATABASE_URL_DIRECT') or os.environ.get('DATABASE_URL')
    if not url: sys.exit('DATABASE_URL not set')
    conn = psycopg2.connect(url); cur = conn.cursor()
    runner = 'github-actions' if os.environ.get('GITHUB_ACTIONS') else 'local'
    cur.execute("insert into ops.sync_runs (job, product, runner, notes) values (%s,%s,%s,'{}') returning run_id", ('{{schema}}.snapshots', '{{schema}}', runner)); conn.commit(); run = cur.fetchone()[0]
    fetched = dt.datetime.now(dt.timezone.utc); n = 0; status = 'ok'; err = None
    try:
        rows = [(run, SOURCE_ID, fetched, r['entity_id'], r.get('entity_name'), r.get('chain'), r.get('value_usd'), r.get('secondary_usd'), r.get('rate_pct'), json.dumps(r.get('payload'))) for r in fetch_rows()]
        psycopg2.extras.execute_values(cur, "insert into {{schema}}.raw_snapshots (run_id, source_id, fetched_at, entity_id, entity_name, chain, value_usd, secondary_usd, rate_pct, payload) values %s", rows, page_size=500)
        conn.commit(); n = len(rows); print(f'[{{schema}}] {n} rows')
    except Exception as e:
        conn.rollback(); status = 'error'; err = str(e)[:500]; print(f'[{{schema}}] FAILED', e)
    cur.execute("update ops.sync_runs set finished_at=now(), status=%s, rows_written=%s, error=%s where run_id=%s", (status, n, err, run))
    cur.execute("""insert into ops.source_freshness (product, source_id, expected_hours, last_seen_at, last_status) values (%s,%s,%s,now(),%s)
                   on conflict (product, source_id) do update set last_seen_at=now(), last_status=excluded.last_status, expected_hours=excluded.expected_hours, updated_at=now()""",
                ('{{schema}}', SOURCE_ID, EXPECTED_HOURS, 'ok' if status == 'ok' else 'broken')); conn.commit()
    sys.exit(0 if status == 'ok' else 1)

if __name__ == '__main__': main()
