-- {{title}} raw layer. Generated by datum-kit on {{today}}; edit freely, it is yours now.
-- Append-only: every row carries run_id, source_id and fetched_at, so any number can be traced to
-- what the source said and when. Payload holds the source's own record for fields the columns miss.
create schema if not exists {{schema}};
create table if not exists {{schema}}.raw_snapshots (
  snapshot_id bigint generated always as identity primary key,
  run_id bigint not null, source_id text not null default '{{source_id}}', fetched_at timestamptz not null,
  entity_id text not null,            -- the thing you snapshot: a pool, market, vault, asset
  entity_name text,
  chain text,
  value_usd double precision,         -- the headline number for the entity (TVL, supply, AUM)
  secondary_usd double precision,     -- the second number (borrowed, redemptions), null if none
  rate_pct double precision,          -- a rate in percent, null if none
  payload jsonb
);
create index if not exists {{schema}}_raw_snapshots_entity_ts on {{schema}}.raw_snapshots (entity_id, fetched_at desc);
create index if not exists {{schema}}_raw_snapshots_fetched on {{schema}}.raw_snapshots (fetched_at);
grant usage on schema {{schema}} to datum_reader;
alter default privileges in schema {{schema}} grant select on tables to datum_reader;
grant select on all tables in schema {{schema}} to datum_reader;
